In [ ]:
# numpy documentation
# https://numpy.org/doc/stable/index.html

NUMPY INSTALLATION

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [5]:
# Importing Numpy Library
import numpy as np

CREATION OF ARRAYS

In [6]:
# creating an array from the list
l=[1,2,3,4]
a=np.array(l)
print(a)

[1 2 3 4]


In [7]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [8]:
type(a)

numpy.ndarray

In [9]:
# creating an array from the tuple
t=(1,2,3,4)
b=np.array((1,2,3,4))
print(b)

[1 2 3 4]


In [10]:
c=np.array([1,2,3,4],dtype='float')
c

array([1., 2., 3., 4.])

In [11]:
c=np.array(['a','b','c','d'],dtype='U1')
c

array(['a', 'b', 'c', 'd'], dtype='<U1')

In [12]:
# Creating 0-D array
arr = np.array(42)
print(arr)

42


In [13]:
# Creating 1-D array
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [14]:
# Creating 2-D array
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [15]:
# Creating 3-D array
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


INSPECTING THE ARRAYS

1. CHECKING DATA TYPES

In [ ]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

In [16]:
a.dtype

dtype('int32')

In [17]:
# checking data types
arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)

<U6


2. CHECKING DIMENSIONS

In [ ]:
#checking dimensions
d.ndim

In [18]:
# creating higher dimensional arrays
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


3. CHECKING SHAPE

In [19]:
# checking the shape
c = np.array([[1, 2, 3], [4, 5, 6]])
c.shape

(2, 3)

In [20]:
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
d.size

12

EXERCISE 1

In [ ]:
# exercise fill the blank to create array
arr = np.     ([1, 2, 3, 4, 5])
# fill with correct argument to create 2D array
arr = np.array([1, 2, 3, 4],    =2)
# check the number of dimensions
arr = np.array([1, 2, 3, 4])
print(arr.   )

ARRAY CREATION - HOMOGENOUS DATA

In [21]:
#creating array of zeros
a=np.zeros((2,3),dtype='int')
a

array([[0, 0, 0],
       [0, 0, 0]])

In [22]:
#creating array of 1's
b=np.ones((3,2))
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [23]:
#creating array with a single value
c=np.full((2,3),'abc')
c

array([['abc', 'abc', 'abc'],
       ['abc', 'abc', 'abc']], dtype='<U3')

ARRAY CREATION - RANDOM NUMBERS

In [25]:
#generates float
x = np.random.rand()
print(x)

0.8519594376459322


In [27]:
#creating array with random values
d=np.random.random((2,3))
d

array([[0.87000584, 0.69620911, 0.7545959 ],
       [0.32692295, 0.33489775, 0.61107084]])

In [28]:
#creating using random integer values in given range
d1=np.random.randint(1,10,(2,4))
print(d1)

[[6 2 5 7]
 [6 3 9 2]]


ARRAY CREATION - NUMERICAL RANGES

In [29]:
#creating array with step size arange(start,end,step)
e=np.arange(1,10,2)
e

array([1, 3, 5, 7, 9])

In [30]:
#creating array with equal spacing
f=np.linspace(1,10,4)
f

array([ 1.,  4.,  7., 10.])

POSITIVE INDEXING

Accessing 1D Array

In [31]:
# accessing 1-D 
# access first element
arr = np.array([1, 2, 3, 4])
print(arr[0])
# to access second element
print(arr[1])
# get 3rd and 4 th and add them
print(arr[2] + arr[3])

1
2
7


Accessing 2D Array

In [32]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [33]:
# to access element on the first row and second column
print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


In [34]:
#access element on the 2nd row and 5th column
print('5th element on 2nd row: ', arr[1, 4])

5th element on 2nd row:  10


Accessing 3D Array

In [36]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [35]:
# accessing 3-d (dimensions and index )
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
# access 3rd of second array of the first array
print(arr[0, 1, 2])

6


In [37]:
# accessing whole row
arr[1,0]

array([7, 8, 9])

Negative Indexing

In [38]:
arr[-2, -1, -1]


6

EXERCISE 2

In [ ]:

#print first item in the array
arr = np.array([1, 2, 3, 4, 5])
print(arr  )
# print 50
arr = np.array([10, 20, 30, 40, 50])
print(arr   )
# print 50
arr = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])
print(arr  )
# print 11
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr )


SLICING

In [39]:
#array slicing
# slicing 1-d array [start:end] [start:end:step]
# slicing from index 1 to 5
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])
#slices from index 4 to the end
print(arr[4:])
# beginning to index 4
print(arr[:4])
# slicing from index 3 to index 1 from the end
print(arr[-3:-1])
# every other element from index 1 to index 5
print(arr[1:5:2])
# every other element from entire array
print(arr[::2])

[2 3 4 5]
[5 6 7]
[1 2 3 4]
[5 6]
[2 4]
[1 3 5 7]


In [40]:
# slicing from index 1 to 5
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [41]:
#slices from index 4 to the end
print(arr[4:])

[5 6 7]


In [42]:
# beginning to index 4
print(arr[:4])

[1 2 3 4]


In [43]:

arr = np.array([1, 2, 3, 4, 5, 6, 7])
# slicing from index 3 to index 1 from the end
print(arr[-3:-1])

[5 6]


In [44]:
# every other element from index 1 to index 5
print(arr[1:5:2])

[2 4]


In [45]:
# every other element from entire array
print(arr[::2])

[1 3 5 7]


In [46]:
# slicing 2-D array
arr = np.array([[1, 2, 3, 4, 5], [6, 7,8 , 9, 10]])
# From the second element, slice from index 1 to index 4 
print(arr[1, 1:4])
# from both return index 2
print(arr[0:2, 2])
# from both elements slice 1 - 4(returns a 2 d array)
print(arr[0:2, 1:4])

[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]


In [ ]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
arr

In [47]:
# From the second element, slice from index 1 to index 4 
print(arr[1, 1:4])

[7 8 9]


In [48]:
# from both return index 2
print(arr[0:2, 2])

[3 8]


In [ ]:
#exercise 3
#1.Everything from (including) the second item to 
#(not including) the fifth item.
arr = np.array([10, 15, 20, 25, 30, 35, 40])
print(arr   )
# 2.Everything from (including) the third item to 
#(not including) the fifth item

#3.Every other item from (including) the second item to 
#(not including) the fifth item.
#4.Every other item from the entire array.

In [49]:
#reshaping
# checking the shape of array
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)

(2, 4)


In [50]:
# reshaping
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [51]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8,9])

newarr = arr.reshape(3, 3)

print(newarr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [52]:
# iterating(1-d)
arr = np.array([1, 2, 3])

for x in arr:
    print(x)

1
2
3


In [53]:
# iterating 2-D
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
    print(x)

[1 2 3]
[4 5 6]


In [54]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


In [55]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


In [56]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [57]:
# iterating using nditer
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8


In [58]:
# joining arrays
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [59]:
# joining rows
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=0)

print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [60]:
#stacking
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [61]:
#Horizontal Stacking, stacks one beside other
arr = np.hstack((arr1, arr2))
arr

array([1, 2, 3, 4, 5, 6])

In [62]:
#Vertical Stacking stacks one above other
arr = np.vstack((arr1, arr2))
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [63]:
#stacking along depth
arr = np.dstack((arr1, arr2))
arr

array([[[1, 4],
        [2, 5],
        [3, 6]]])

In [64]:
#exercise 4
# Use a correct NumPy method to join two arrays into a single array.
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))
arr

array([1, 2, 3, 4, 5, 6])

In [65]:
# split arrays

arr = np.array([1, 2, 3, 4, 5, 6])
# splits in 3 parts
newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [66]:
arr = np.array([1, 2, 3, 4, 5, 6])
# splits in 3 parts
newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [67]:
# Splitting 2-dimensional
a=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(a)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [68]:
# horizontal splitting
print("Splitting along horizontal axis into 2 parts:\n", np.hsplit(a, 2))

Splitting along horizontal axis into 2 parts:
 [array([[1, 2, 3],
       [7, 8, 9]]), array([[ 4,  5,  6],
       [10, 11, 12]])]


In [69]:
#Vertical Split
print("Splitting along Vertical axis into 2 parts:\n", np.vsplit(a, 2))

Splitting along Vertical axis into 2 parts:
 [array([[1, 2, 3, 4, 5, 6]]), array([[ 7,  8,  9, 10, 11, 12]])]


In [70]:
# search
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6], dtype=int64),)


In [71]:
# search even number
x = np.where(arr%2 == 0)
x

(array([1, 3, 5, 6], dtype=int64),)

In [72]:
# search odd number
x = np.where(arr%2 == 1)
x

(array([0, 2, 4], dtype=int64),)

In [73]:
# sort
arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [74]:
# sorts alphabetically
arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']
